name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_NUMBER: ${{ 42 }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_ARRAY: '["one", "two", "three"]'
          LITERAL_OBJECT: '{"key": "value"}'